### PR TITLE
Fixed your instructions

### PR DESCRIPTION
**Pull request by npxl32**
PLEASE READ THE FULL PULL REQUEST DESCRIPTION
1. I fixed your branches instructions I don't think you even read the README when I make pull requests
2. Added a part about how Git works on a high level.  Seriously it's important to know how your software works at some degree. In that respect, you shouldn't have deleted the .NET part from the other pull request either. You could have deleted a lot of stuff, but you shouldn't have removed the lines that explains how it works.
3. Added a part about Visual Studio. Sure, you could code a console application, or even a website without it, but a game? Coding a game with notepad is &lt;I don't think github will let me say this word&gt;. Visual Studio Code might also be somewhat viable but I still think it's better to use Visual Studio. [The official site](https://visualstudio.microsoft.com/downloads/#picker) also recommends Visual Studio if you pick .NET, C#, and games.

### CODE REVIEW

**Comment by saverofthewos** [comment]
We aren't coding with notepad? Godot? Hello?

**Comment by npxl32** [comment]
> We aren't coding with notepad? Godot? Hello?

Godot is the engine. You would still have to write scripts in notepad. @saverofthewos

**Comment by saverofthewos** [comment]
No, Godot has a built in script editor. Does unity not?

**Comment by npxl32** [comment]
> No, Godot has a built in script editor. Does unity not?

Wait what? No Unity does *not* have a built in script editor. The closest thing they have to that is previewing the plaintext in a script. Then when you open the script, Visual Studio or whatever code editor you said it should use will open. 

I think it's still good to use Visual Studio optionally.

**Comment by saverofthewos** [comment]
And that's why you don't use unity.

**Comment by npxl32** [comment]
> And that's why you don't use unity.

What do you have against Unity?

Literally everything does that, this isn't specific to Unity.

Unity is a great engine. Just that the company behind it is bad. (I mean come on the CEO was too greedy for EA)

Godot is a rare case, it's not usual that something has a text editor in the first place.

**Comment by npxl32** [comment]
> And that's why you don't use unity.

What do you have against Unity?

Literally everything does that, this isn't specific to Unity.

 I don't like that Godot has a text editor in the first place.

**Comment by saverofthewos** [comment]
https://www.outlookindia.com/international/us/unity-technologies-to-charge-developers-every-time-their-game-is-installed-news-317674

**Comment by npxl32** [comment]
Outlook India?? Man, I didn't know they were that popular. All those inside jokes with my friend group...
Anyways. Yes, I know about that. They changed the terms of that thing so that it's way fairer. First you need one million downloads. [See here.](https://www.ign.com/articles/unity-has-apologized-for-its-install-fee-policy-and-says-it-will-be-making-changes-to-it)

**Comment by saverofthewos** [comment]
It also takes an hour to install and you can't do anything without googling it because of the ui

**Comment by npxl32** [comment]
> It also takes an hour to install and you can't do anything without googling it because of the ui

For my internet (normal internet) it's 30 minutes but yeah, I can agree they added a lot of bloat, it used to be only 10 minutes and 5GB instead of 12GB.

"Can't do anything without Googling it"? What? Does that mean that it's hard to navigate the UI at first? That applies to a lot of stuff, although surprisingly Unity is more usable than other game engines.

**Comment by saverofthewos** [comment]
i tried 4 game engines and unity was the most complicated

**Comment by npxl32** [comment]
> i tried 4 game engines and unity was the most complicated

Oh...
They added too much bloat...

**Comment by saverofthewos** [comment]
I tried one really obscure engine I can't remember the name (like felicia or smth)
godot
i almost tried UE and then it made me install epic games launcher (which i don't trust)
unity
gamemaker (too much paid features)

**Comment by npxl32** [comment]
> I tried one really obscure engine I can't remember the name (like felicia or smth) godot i almost tried UE and then it made me install epic games launcher (which i don't trust) unity gamemaker (too much paid features)

gamemaker is really simplified
unreal - uh why dont u trust epic games launcher (chinese spyware) and unreal is very *not* simple
godot - ok idk how this is any simpler than unity
u didnt try a single C++ engine. gamemaker is fake programming language, unreal is c++, unity is c#, and godot is c# and a bunch of other stuff + fake programming language (i mean super oversimplified when i say that, for example for me python falls under this category, its just less syllables thats why i say it)

**Comment by saverofthewos** [comment]
i literally don't care what the programming language is for a game engine as long as i can learn

**Comment by saverofthewos** [comment]
and simple languages are good

**Comment by npxl32** [comment]
1. The following game engines were meant to be simplified; you tried all the simplified ones:
- Unity 
- Clickteam (debatable)
- Godot
- GameMaker
- pygame
- scratch (debatable)
- more but i dont want to think

**Comment by saverofthewos** [comment]
> > I tried one really obscure engine I can't remember the name (like felicia or smth) godot i almost tried UE and then it made me install epic games launcher (which i don't trust) unity gamemaker (too much paid features)
> 
> gamemaker is really simplified unreal - uh why dont u trust epic games launcher (chinese spyware) and unreal is very _not_ simple godot - ok idk how this is any simpler than unity u didnt try a single C++ engine. gamemaker is fake programming language, unreal is c++, unity is c#, and godot is c# and a bunch of other stuff + fake programming language (i mean super oversimplified when i say that, for example for me python falls under this category, its just less syllables thats why i say it)

i didn't try unreal
i know how unsimple it is it's meant for "good games" (games that look pretty but have almost no gameplay)

**Comment by npxl32** [comment]
2. [www.npxl32.com](https://www.npxl32.com/) successful migration to .NET 8. really it was only changing the tfm, github actions workflow, and azure runtime settings

**Comment by npxl32** [comment]
> > > I tried one really obscure engine I can't remember the name (like felicia or smth) godot i almost tried UE and then it made me install epic games launcher (which i don't trust) unity gamemaker (too much paid features)
> > 
> > 
> > gamemaker is really simplified unreal - uh why dont u trust epic games launcher (chinese spyware) and unreal is very _not_ simple godot - ok idk how this is any simpler than unity u didnt try a single C++ engine. gamemaker is fake programming language, unreal is c++, unity is c#, and godot is c# and a bunch of other stuff + fake programming language (i mean super oversimplified when i say that, for example for me python falls under this category, its just less syllables thats why i say it)
> 
> i didn't try unreal i know how unsimple it is it's meant for "good games" (games that look pretty but have almost no gameplay)

good games can have gameplay, like goat simulator or fortnite. some really good games.

**Comment by npxl32** [comment]
> 2. [www.npxl32.com](https://www.npxl32.com/) successful migration to .NET 8. really it was only changing the tfm, github actions workflow, and azure runtime settings

as such, a new tool has been released in celebration of the migration: Link preview generator

**Pull request merged**
